name: wekeep
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_sign_in: ^5.4.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  file_picker: ^5.5.0
  image_picker: 0.8.5+3
  flutter_colorpicker: 1.0.3
  select_form_field: 2.2.0
  maps_launcher: ^2.2.0
  url_launcher: ^6.1.5
  flutter_email_sender: 5.1.0
  geoflutterfire2: ^2.3.15
  geolocator: 9.0.1
  flutter_local_notifications: ^9.7.0
  http: ^0.13.5
  flutter_svg: ^1.1.5
  getwidget: ^2.0.4
  flutter_signin_button: ^2.0.0
  onesignal_flutter: ^3.5.1
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  firebase_core_platform_interface: ^4.8.0
  firebase_messaging:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
